CREATE TABLE CUSTOMER_ORDER_DETAILS (
  ORDER_ID identity  PRIMARY KEY ,
  CUSTOMER_NAME VARCHAR2(100),
  ORDER_DATE DATE,
  ADDRESS_LINE1 VARCHAR2(100),
  CITY VARCHAR2(100),
  STATE VARCHAR2(100),
   ZIP NUMBER(5),
  BILLED_AMOUNT   NUMBER(10,2));
  
  CREATE TABLE CUSTOMER_ITEM_ORDER (
  ORDER_ID NUMBER NOT NULL,
  product_code VARCHAR2(20) NOT NULL,
  quantity   NUMBER);
  
  alter table CUSTOMER_ITEM_ORDER ADD CONSTRAINT PK_CUSTID  primary key (ORDER_ID,product_code)